name: Build Report

on:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Restore renv environment
      run: R -e 'install.packages("renv"); renv::restore()'

    - name: Render report
      run: |
        quarto render report.qmd --to html --output docs/report.html
        quarto render report.qmd --to pdf --output docs/report.pdf

    - name: Upload artifacts (optional)
      uses: actions/upload-artifact@v3
      with:
        name: report-files
        path: docs/